title: EMLG/JMLG 2026
description: Programme and book of abstracts for EMLG/JMLG 2026
url: "https://emlg-2026.github.io"
baseurl: ""

theme: jekyll-theme-conference

plugins:
  - jekyll-include-cache

collections:
  talks:
    output: true
    permalink: /abstracts/:title/
  posters:
    output: true
    permalink: /posters/:name/
  speakers:
    output: true
    permalink: /speakers/:title/
  rooms:
    output: true
    permalink: /rooms/:title/


defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      overview_url: /sessions/
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: posters
    values:
      layout: poster
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:
  lang: en
  tz: "+01:00"
  show_errors: true

  talks:
    tracks:
      - name: Social / Other
        color: secondary
      - name: EMLG/JMLG School
        color: secondary
      - name: Session 1
        color: success
      - name: Session 2
        color: info
      - name: Session 3
        color: warning
      - name: Session 4
        color: primary
      - name: Session 5
        color: danger
      - name: Session 6
        color: success
      - name: Session 7
        color: info
      - name: Session 8
        color: warning
      - name: Session 9
        color: primary
      - name: Session 10
        color: danger
      - name: Session 11
        color: success



  navigation:
    links:
      - name: Programme
        icon: calendar4-week
        relative_url: /program/
      - name: Sessions
        icon: journal-text
        relative_url: /sessions/
      - name: Speakers
        icon: people
        relative_url: /speakers/
      - name: Posters
        icon: easel
        relative_url: /posters/
      - name: Book of Abstracts
        icon: file-earmark-pdf
        relative_url: /documents/emlg-jmlg-2025-book-of-abstracts.pdf
